Define and implement a Storage Facility microsite.

diff --git a/scripts/demo/commands/expand b/scripts/demo/commands/expand
--- a/scripts/demo/commands/expand
+++ b/scripts/demo/commands/expand
@@ -14,7 +14,7 @@ source "$SCRIPT_HOME/shell.subr" || {
 # MAIN
 ########################################################################
 
-[[ $# -gt 1 ]] || err 2 "missing expand enum\n\nSee demo.sh --help"
+[[ $# -gt 1 ]] || err 2 "missing expand enum\n\nSee demo.sh -h"
 
 if [[ -z "${QUERY_PARAMETERS:-}" ]]
 then
